# Use the official RHEL 9 base image
FROM registry.access.redhat.com/ubi9/ubi:latest

# Switch to root user
USER root

# Set environment variables for MUNGE and SLURM users
ENV MUNGEUSER=1001

# Enable the required repositories and install necessary packages
RUN dnf install -y munge && \
    dnf install -y munge-libs && \
    dnf install -y munge-devel --enablerepo=codeready-builder-for-rhel-9-$(arch)-rpms && \
    # Check if the group exists before adding
    if ! getent group munge > /dev/null; then groupadd -g $MUNGEUSER munge; fi && \
    if ! getent passwd munge > /dev/null; then useradd -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u $MUNGEUSER -g munge -s /sbin/nologin munge; fi && \
    dnf clean all && \
    /usr/sbin/create-munge-key -r && \
    chown 1001:1001 /etc/munge/munge.key && \
    chmod 0644 /etc/munge/munge.key && \
    chown 1001:1001 /etc/munge && \
    chmod 0755 /etc/munge && \
    curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz" && \
    tar -xvzf openshift-client-linux.tar.gz && \
    mv oc /usr/local/bin/oc && chmod +x /usr/local/bin/oc

# Set the default command
CMD ["/bin/bash", "-c", "oc create secret generic munge-key-secret --from-file=/etc/munge/munge.key || echo 'Failed to create secret'; sleep ${SLEEP_DURATION:-10}; exec /bin/bash"]