# Use the official RHEL 9 base image
FROM registry.access.redhat.com/ubi9/ubi:latest

# Switch to root user for installation
USER root

# Create the munge and slurm users and groups
RUN groupadd -g 1001 munge && \
    useradd -m -u 1001 -g munge -d /var/lib/munge -s /sbin/nologin -c "MUNGE Uid 'N' Gid Emporium" munge && \
    groupadd -g 1002 slurm && \
    useradd -m -u 1002 -g slurm -d /var/lib/slurm -s /sbin/nologin -c "SLURM workload manager" slurm

# Install necessary packages for munge
RUN dnf install -y munge munge-libs munge-devel slurm slurmctld slurmd --enablerepo=codeready-builder-for-rhel-9-$(arch)-rpms && \
    mkdir -p /run/munge /var/lib/munge /var/log/munge && \
    chown -R 1001:1001 /run/munge /var/lib/munge /var/log/munge && \
    chmod 755 /run/munge && chmod 700 /var/lib/munge && chmod 755 /var/log/munge && \
    dnf clean all

# Copy the munge key from the build context
COPY /tmp/munge.key /etc/munge/munge.key

# Ensure correct ownership and permissions for the key
RUN chown 1001:1001 /etc/munge/munge.key && chmod 400 /etc/munge/munge.key

# Copy entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Install necessary packages for slurm

# Use root user initially, then switch in the script
USER root

# Run the entrypoint script
CMD ["/usr/local/bin/entrypoint.sh"]
