---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: munge-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: munge-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: munge-secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: munge-sa
roleRef:
  kind: Role
  name: munge-secret-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: custom-scc-munge
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
runAsUser:
  type: RunAsAny
  uid: 1001
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny
