apiVersion: batch/v1
kind: Job
metadata:
  name: munge-key-and-secret-generator-job
spec:
  template:
    spec:
      serviceAccountName: munge-sa
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: munge-key-and-secret-generator
          image: quay.io/rcardona/munge-key-and-secret-generator:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          runAsNonRoot: true
          runAsUser: 1001
      restartPolicy: OnFailure