apiVersion: batch/v1
kind: Job
metadata:
  name: munge-key-and-secret-generator-job
spec:
  template:
    spec:
      serviceAccountName: munge-sa
      containers:
        - name: munge-key-and-secret-generator
          image: quay.io/rcardona/munge-key-and-secret-generator:v1
          securityContext:
            runAsUser: 0  # Start as root
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
      restartPolicy: OnFailure