apiVersion: apps/v1
kind: Deployment
metadata:
  name: munge-process
  labels:
    app: munge-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: munge-process
  template:
    metadata:
      labels:
        app: munge-process
    spec:
      serviceAccountName: munge-sa   # Use custom service account
      containers:
        - name: munge-process
          image: quay.io/rcardona/munge-process:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          runAsNonRoot: true
          runAsUser: 1001
          volumeMounts:
            - name: munge-key-volume
              mountPath: /etc/munge/munge.key
              subPath: munge.key
      volumes:
        - name: munge-key-volume
          secret:
            secretName: munge-key-secret
