apiVersion: v1
kind: Pod
metadata:
  name: slurmctl-process
  labels:
    app: slurmctl-process
spec:
  serviceAccountName: munge-sa
  containers:
    - name: slurmctl-process
      image: quay.io/rcardona/slurmctl-process:latest
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: slurmdbd-config-volume
          mountPath: /tmp/slurmdbd.conf
          subPath: slurmdbd.conf
      resources:
          limits:
            memory: "2Gi"   # Maximum memory limit for the container
          requests:
            memory: "1Gi"
  volumes:
    - name: slurmdbd-config-volume
      configMap:
        name: slurmdbd-config
