apiVersion: v1
kind: Pod
metadata:
  name: slurmctl-munge
  labels:
    app: slurmctl-munge
spec:
  serviceAccountName: munge-sa
  containers:
    - name: slurmctl-munge-process
      image: quay.io/rcardona/slurmctl-munge:latest
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: munge-key-volume
          mountPath: /tmp/munge.key
          subPath: munge.key
        - name: slurmdbd-config-volume
          mountPath: /tmp/slurmdbd.conf
          subPath: slurmdbd.conf
      # resources:
      #     limits:
      #       memory: "2Gi"   # Maximum memory limit for the container
      #     requests:
      #       memory: "1Gi"
  volumes:
    - name: munge-key-volume
      secret:
        secretName: munge-key-secret
    - name: slurmdbd-config-volume
      configMap:
        name: slurmdbd-config
    