apiVersion: v1
kind: Pod
metadata:
  name: base-tools
  labels:
    app: base-tools
spec:
  serviceAccountName: munge-sa
  containers:
    - name: base-tools-process
      image: quay.io/rcardona/base-tools:latest
      ports:
        - containerPort: 22
          name: ssh
      securityContext:
        privileged: true
        runAsUser: 0
        allowPrivilegeEscalation: true
