apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scc-munge-binding
roleRef:
  apiGroup: security.openshift.io
  kind: SecurityContextConstraints
  name: custom-scc-munge
subjects:
- kind: ServiceAccount
  name: munge-sa
