---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: munge-scc
allowPrivilegedContainer: false
allowRunAsUser: true
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1001
  uidRangeMax: 1001
seLinuxContext:
  type: RunAsAny