apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurm
  labels:
    app: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurm
  template:
    metadata:
      labels:
        app: slurm
    spec:
      serviceAccountName: munge-sa
      containers:
        - name: munge-process
          image: quay.io/rcardona/munge-process:latest
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1001
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: munge-key-volume
              mountPath: /tmp/munge.key
              subPath: munge.key
      volumes:
        - name: munge-key-volume
          secret:
            secretName: munge-key-secret