# Use the official RHEL 9 base image
FROM registry.access.redhat.com/ubi9/ubi:latest

# Install required tools: munge and oc (client tools)
RUN dnf install -y munge munge-libs munge-devel --enablerepo=codeready-builder-for-rhel-9-$(arch)-rpms && \
    dnf clean all && \
    # Download and install the OpenShift client
    curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz" && \
    tar -xvzf openshift-client-linux.tar.gz && \
    mv oc /usr/local/bin/oc && chmod +x /usr/local/bin/oc && \
    rm -f openshift-client-linux.tar.gz kubectl

# copy create-munge-key to write to container image
COPY create-munge-key /usr/sbin/create-munge-key
RUN chmod +x /usr/sbin/create-munge-key

# Add the entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set working directory
WORKDIR /mnt/munge

# Set entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]