# Use the official RHEL 9 base image
FROM registry.access.redhat.com/ubi9/ubi:latest

# Switch to root user
USER root

# Set environment variables for MUNGE user
ENV MUNGEUSER=1001

# Install necessary packages
RUN dnf install -y munge munge-libs munge-devel --enablerepo=codeready-builder-for-rhel-9-$(arch)-rpms && \
    dnf clean all && \
    # Download and install the OpenShift client
    curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz" && \
    tar -xvzf openshift-client-linux.tar.gz && \
    mv oc /usr/local/bin/oc && chmod +x /usr/local/bin/oc && \
    rm -f openshift-client-linux.tar.gz kubectl

# Copy entrypoint script into the image
#COPY slurm-munge-secret-generator-entrypoint.sh /slurm-munge-secret-generator-entrypoint.sh
COPY test.sh /test.sh

# Make entrypoint script executable
#RUN chmod +x /slurm-munge-secret-generator-entrypoint.sh
RUN chmod +x /test.sh

# Set the entrypoint
#ENTRYPOINT ["/slurm-munge-secret-generator-entrypoint.sh"]
ENTRYPOINT ["/test.sh"]