---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: munge-secret-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: munge-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "delete", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: munge-secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: munge-secret-sa
roleRef:
  kind: Role
  name: munge-secret-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: munge-secret-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
  uid: 1001
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slurm-sa

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: slurm-scc
allowPrivilegedContainer: true  # Only if necessary
allowPrivilegeEscalation: true  # Only if necessary
runAsUser:
  type: RunAsAny  # Allows running as any UID
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny