apiVersion: batch/v1
kind: Job
metadata:
  name: munge-key-secret-generator-job
spec:
  template:
    spec:
      serviceAccountName: munge-secret-sa
      containers:
        - name: munge-key-and-secret-generator
          image: quay.io/rcardona/munge-notest:1.5
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: munge-dir
              mountPath: /mnt/munge
          env:
            - name: SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SECRET_NAME
              value: munge-key-secret
      volumes:
        - name: munge-dir
          emptyDir: {}
      restartPolicy: OnFailure