apiVersion: batch/v1
kind: Job
metadata:
  name: munge-key-secret-generator-job
#spec:
#  template:
#    spec:
#      serviceAccountName: munge-secret-sa
#      containers:
#        - name: munge-key-and-secret-generator
#          image: quay.io/rcardona/munge-key-secret-generator:latest
#          securityContext:
#            runAsUser: 0  # Start as root
#            allowPrivilegeEscalation: true
#            capabilities:
#              drop:
#                - ALL
#      volumes:
#      - name: munge-dir
#        emptyDir: {}
#      restartPolicy: OnFailure
spec:
  template:
    spec:
      serviceAccountName: munge-secret-sa
      containers:
        - name: munge-key-and-secret-generator
          image: quay.io/rcardona/munge-key-secret-generator:latest
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: munge-dir
              mountPath: /mnt/munge
      volumes:
        - name: munge-dir
          emptyDir: {}
      restartPolicy: OnFailure


